cmdb/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from cmdb import views,api,asset_info

urlpatterns = [
    url(r'^idc$', views.idc_list,name='cmdb_idc'),
    url(r'^idc/add$', views.idc_add,name='cmdb_idc_add'),
    url(r'^idc/edit$', views.idc_edit,name='cmdb_idc_edit'),
    url(r'^idc/del$', views.idc_del,name='cmdb_idc_del'),

    #IDC Search
    url(r'^idc/search$', api.idc_search,name='idc_search'),
    #Server Search
    url(r'^asset/search$', api.asset_search,name='asset_search'),

    #Server Assets
    url(r'^server$', views.server_list, name='cmdb_server'),
    url(r'^server/add$', views.server_add, name='cmdb_server_add'),
    url(r'^server/detail/(?P<uuid>[a-f\d]{8}(-[a-f\d]{4}){3}-[a-f\d]{12}?)$', views.server_detail, name='cmdb_server_detail'),
    url(r'^server/edit/(?P<uuid>[a-f\d]{8}(-[a-f\d]{4}){3}-[a-f\d]{12}?)$', views.server_edit, name='cmdb_server_edit'),
    url(r'^server/del$', views.server_del, name='cmdb_server_del'),

    #更新主机
    url(r'^update$', asset_info.update_assets_info, name='cmdb_server_update'),
    url(r'^export$', asset_info.export_assets_info, name='cmdb_server_export'),
]

ops/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import url,include
from django.contrib import admin
from cmdb import views as cmdb_views
from accounts import urls
from dashboard import urls
from dashboard import views as dashboard_views
import saltapi

urlpatterns = [
	url(r'^$', dashboard_views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^/dashboard/', include('dashboard.urls')),
    url(r'accounts/', include('accounts.urls')),
    url(r'cmdb/', include('cmdb.urls')),
    url(r'salt/', include('saltapi.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^admin/', admin.site.urls),
]

cmdb/models.py
from django.db import models
import uuid
from django.utils import timezone
from saltapi.models import Salt
from accounts.models import User

class ISP(models.Model):

  name = models.CharField(unique=True,max_length=64, verbose_name=u'运营商')

  def __str__(self): 
      return self.name

class IDC(models.Model):

    uuid = models.UUIDField(blank=True,primary_key=True, auto_created=True, default=uuid.uuid4)
    name = models.CharField(unique=True,max_length=64, verbose_name=u'机房名称')
    isp = models.ForeignKey(ISP,null=True,on_delete=models.SET_NULL,verbose_name=u'运营商名称')
    address = models.CharField(max_length=64, verbose_name=u'机房地址')
    contact = models.CharField(max_length=32, verbose_name=u'联系人')
    phone = models.CharField(max_length=32, verbose_name=u'联系电话')
    network = models.TextField(blank=True,null=True, verbose_name=u'IP地址段')
    comment = models.TextField(blank=True,null=True, verbose_name=u'备注')
    update_time = models.DateTimeField(blank=True,default=timezone.now, verbose_name='更新时间')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name=u'创建时间')

    def __str__(self): 
        return self.name

    class Meta:
      verbose_name = u'机房管理'
      verbose_name_plural = verbose_name 

class ServerAsset(models.Model):

    operation_status = (
      (1,'运营中'),
      (2,'未上线'),
      (3,'故障中'),
      (4,'维修中'),
      (5,'开发机'),
      (6,'测试机'),
      (7,'下线'),
      )
    minion_status = (
      (1,'正常'),
      (2,'未安装'),
      )
    
    uuid = models.UUIDField(blank=True,primary_key=True, auto_created=True, default=uuid.uuid4)

    hostname = models.CharField(max_length=50,verbose_name=u'主机名')
    ip = models.GenericIPAddressField(unique=True, verbose_name=u'IP')
    idc = models.ForeignKey(IDC, blank=True, null=True,on_delete=models.SET_NULL,verbose_name=u'机房')
    salt = models.ForeignKey(Salt,blank=True, null=True,on_delete=models.SET_NULL,verbose_name=u'Salt-Master')
    status = models.IntegerField(choices=operation_status,verbose_name=u'状态',default=1)
    ops = models.ForeignKey(User, blank=True, null=True,on_delete=models.SET_NULL,related_name='ops',verbose_name=u'运维负责人')
    dev = models.ForeignKey(User, blank=True, null=True,on_delete=models.SET_NULL,related_name='dev',verbose_name=u'开发负责人')
    manufacturer = models.CharField(max_length=20, blank=True, verbose_name=u'厂商')
    productname = models.CharField(max_length=100, blank=True, verbose_name=u'型号')
    sn = models.CharField(max_length=100, blank=True, verbose_name=u'序列号')
    cpu_model = models.CharField(max_length=100, blank=True, verbose_name=u'CPU型号')
    cpu_nums = models.PositiveSmallIntegerField(blank=True,verbose_name=u'CPU线程', default=0)
    memory = models.CharField(max_length=20,blank=True, verbose_name=u'内存')
    disk = models.TextField(blank=True, verbose_name=u'硬盘')

    os = models.CharField(max_length=200, blank=True, verbose_name=u'操作系统')
    virtual = models.CharField(max_length=20, blank=True, verbose_name=u'虚拟化')
    kernel = models.CharField(max_length=200, blank=True, verbose_name=u'内核')
    shell = models.CharField(max_length=10, blank=True, verbose_name=u'Shell')
    selinux = models.CharField(max_length=50, blank=True, verbose_name=u'Selinux')
    locale = models.CharField(max_length=200, blank=True, verbose_name=u'编码')

    saltversion = models.CharField(max_length=10, blank=True, verbose_name=u'Salt版本')
    minion_status = models.IntegerField(choices=minion_status,verbose_name=u'Minion状态',default=2)

    update_time = models.DateTimeField(blank=True,default=timezone.now, verbose_name='更新时间')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name=u'创建时间')

    def __unicode__(self):
        return self.hostname
    
    class Meta:
        # default_permissions = ()
        # permissions = (
        #     ("view_asset", u"查看资产"),
        #     ("edit_asset", u"管理资产"),
        # )
        verbose_name = u'主机资产信息'
        verbose_name_plural = u'主机资产信息管理'


class NetworkInterface(models.Model):

    name = models.CharField(max_length=15, verbose_name=u'网卡名称')
    address = models.CharField(max_length=15,verbose_name=u'IP地址')
    mac = models.CharField(max_length=17,verbose_name=u'Mac地址')
    server = models.ForeignKey(ServerAsset, null=True, on_delete=models.SET_NULL, verbose_name=u'主机' )

    def __str__(self):
        return self.name

    class Meta:

      unique_together = (('name', 'server'),)
      verbose_name = u'网卡管理'
      verbose_name_plural = verbose_name 

cmdb/forms.py
#-*- coding: utf-8 -*-
from django import forms
from cmdb.models import IDC, ServerAsset
 
class IDCForm(forms.ModelForm):

    class Meta:
        model = IDC
        exclude = ('uuid','create_time','update_time')
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control'}),
            'isp' : forms.Select(attrs={'class':'form-control'}),
            'address' : forms.TextInput(attrs={'class':'form-control'}),
            'contact' : forms.TextInput(attrs={'class':'form-control'}),
            'phone' : forms.TextInput(attrs={'class':'form-control'}),
            'network' : forms.Textarea(attrs={'class':'form-control'}),
            'comment' : forms.Textarea(attrs={'class':'form-control','rows': '7'})
       }


class ServerAssetForm(forms.ModelForm):


    def __init__(self, *args, **kwargs):
        super(ServerAssetForm, self).__init__(*args, **kwargs)
        field = ['salt','manufacturer','productname','virtual','cpu_model','cpu_nums','memory','disk','os','virtual','kernel','shell','selinux', 'locale','saltversion']
        for i in field:
            self.fields[i].required = False 

    class Meta:
        model = ServerAsset
        exclude = ('uuid', 'hostname', 'create_time', 'update_time')
        widgets = {
        
            'ip' : forms.Textarea(attrs={'class':'form-control'}),
            'idc' : forms.Select(attrs={'class':'form-control'}),
            'salt' : forms.Select(attrs={'class':'form-control'}),
            'status' : forms.Select(attrs={'class':'form-control'}),
            
            'ops' : forms.Select(attrs={'class':'form-control'}),
            'dev' : forms.Select(attrs={'class':'form-control'}),

            'manufacturer' : forms.TextInput(attrs={'class':'form-control'}),
            'productname' : forms.TextInput(attrs={'class':'form-control'}),
            'virtual' : forms.TextInput(attrs={'class':'form-control'}),
            'sn' : forms.TextInput(attrs={'class':'form-control'}),

            'cpu_model' : forms.TextInput(attrs={'class':'form-control'}),
            'cpu_nums' : forms.TextInput(attrs={'class':'form-control'}),
            'memory' : forms.TextInput(attrs={'class':'form-control'}),
            'network' : forms.TextInput(attrs={'class':'form-control'}),
            'disk' : forms.TextInput(attrs={'class':'form-control'}),

            'os' : forms.TextInput(attrs={'class':'form-control'}),
            'virtual' : forms.TextInput(attrs={'class':'form-control'}),
            'kernel' : forms.TextInput(attrs={'class':'form-control'}),
            'shell' : forms.TextInput(attrs={'class':'form-control'}),
            'selinux' : forms.TextInput(attrs={'class':'form-control'}),
            'locale' : forms.TextInput(attrs={'class':'form-control'}),

            'saltversion' : forms.TextInput(attrs={'class':'form-control'}),

       }

cmdb/views.py
#-*- coding: utf-8 -*-
'''
	Author: Geekwolf
	Blog: http://www.simlinux.com
'''
from django.shortcuts import render,render_to_response,reverse
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from commons.paginator import paginator
import json,logging
from cmdb.models import IDC, ServerAsset, NetworkInterface
from cmdb.forms import IDCForm, ServerAssetForm
from commons.handle import uuid_rm,ip_lists
from django import forms
from django.shortcuts import get_object_or_404,redirect
from cmdb.asset_info import update_assets_info

def gentella_html(request):
    context = {}
    # The template to be loaded as per gentelella.
    # All resource paths for gentelella end in .html.

    # Pick out the html file name from the url. And load that template.
    load_template = request.path.split('/')[-1]
    template = loader.get_template('app/' + load_template)
    return HttpResponse(template.render(context, request))

def idc_list(request):

    data = {}
    idc = IDC.objects.all().order_by('-update_time')
    data = paginator(request, idc)
    request.breadcrumbs((('首页', '/'),('机房管理',reverse('cmdb_idc'))))

    return render(request, 'cmdb/idc/idc.html', {'request': request, 'data': data})

def idc_add(request):

    error = ""
    if request.method == "POST":
        new_name = request.POST.get('name')
        name = IDC.objects.filter(name=new_name)
        form = IDCForm(request.POST)
        if name:
            error = u'该机房记录已存在，请更换名称!'
        else:
            if form.is_valid():
                tmp = form.save(commit=False)
                tmp.save()
                return HttpResponseRedirect(reverse('cmdb_idc'))
    else:
        form = IDCForm()
    request.breadcrumbs((('首页', '/'),('机房管理',reverse('cmdb_idc')),('添加机房',reverse('cmdb_idc_add'))))

    return render(request, 'cmdb/idc/idc_add.html', {'request': request, 'form': form, 'error': error})

def idc_edit(request):

    error = ""
    uuid = uuid_rm(request.GET.get("uuid"))
    if uuid:
        try:
            idc = IDC.objects.select_related().get(uuid=uuid)
            form = IDCForm(instance=idc)
        except:
            error = "不存在"
            form = ""
    if request.method == "POST":
        idc = IDC.objects.select_related().get(uuid=uuid)
        form = IDCForm(request.POST,instance=idc)
        if form.is_valid():
            tmp = form.save(commit=False)
            tmp.save()
            return HttpResponseRedirect(reverse('cmdb_idc'))
    request.breadcrumbs((('首页', '/'),('机房管理',reverse('cmdb_idc')),('编辑机房',reverse('cmdb_idc_edit'))))

    return render(request, 'cmdb/idc/idc_edit.html', {'request': request, 'form': form, 'uuid': uuid,'error': error})

def idc_del(request):

    uuid = request.GET.get('uuid')
    if uuid:
        IDC.objects.filter(uuid=uuid).delete()
    return HttpResponseRedirect(reverse('cmdb_idc'))


def server_list(request):

    data = {}
    # server = ServerAsset.objects.all().order_by('-update_time')
    server = ServerAsset.objects.raw('SELECT s.uuid,s.hostname,s.status,s.productname,s.cpu_model,s.memory,s.disk,s.os,s.virtual,s.kernel,s.ops_id,s.dev_id,s.minion_status,GROUP_CONCAT(n.address)as ips  from cmdb_serverasset s LEFT JOIN cmdb_networkinterface n on s.uuid = n.server_id GROUP BY s.uuid;')
    data = paginator(request, list(server))
    data['fields'] = ServerAsset._meta.get_fields()
    
    request.breadcrumbs((('首页', '/'),('主机管理',reverse('cmdb_server'))))

    return render(request, 'cmdb/assets/server.html', {'request': request, 'data': data})



def server_add(request):

    error = ""
    if request.method == "POST":
        
        ip_input = request.POST.get('ip').split('\n')
        ips = ip_lists(ip_input)
        uuids = []
        for i in ips:
            data = request.POST.copy()
            data['ip'] = i
            form = ServerAssetForm(data)
            if form.is_valid():
                tmp = form.save(commit=False)
                tmp.save()
                uuids.append(tmp.uuid)
        update_assets_info(request,uuids=uuids,type="server_add")
        return HttpResponseRedirect(reverse('cmdb_server'))
    else:
        form = ServerAssetForm()
    request.breadcrumbs((('首页', '/'),('主机管理',reverse('cmdb_server')),('添加主机',reverse('cmdb_server_add'))))
    return render(request, 'cmdb/assets/server_add.html', {'request': request, 'form': form, 'error': error})


def server_edit(request,uuid):

    error = ""
    server = get_object_or_404(ServerAsset,uuid = uuid)
    form = ServerAssetForm(instance=server)
    if request.method == "POST":
        server = ServerAsset.objects.select_related().get(uuid=uuid)
        form = ServerAssetForm(request.POST,instance=server)
        if form.is_valid():
            tmp = form.save(commit=False)
            tmp.save()
            return HttpResponseRedirect(reverse('cmdb_server'))
    request.breadcrumbs((('首页', '/'),('主机管理',reverse('cmdb_server')),))
    return render(request, 'cmdb/assets/server_edit.html', {'request': request, 'form': form, 'uuid': uuid,'error': error})



def server_del(request):

    uuid = request.GET.get('uuid')
    uuids = []

    if uuid: 
        uuids = [uuid]
    if request.POST.get('type') == 'bulk_delete':
        print(request.POST.get('type'))
        uuids = [ uuid_rm(i) for i in json.loads(request.POST.get('servers'))]

    NetworkInterface.objects.filter(server__in = uuids).delete()
    ServerAsset.objects.filter(uuid__in = uuids).delete()

    return HttpResponseRedirect(reverse('cmdb_server'))


def server_detail(request,uuid):

    data = {}
    serverasset = get_object_or_404(ServerAsset,uuid = uuid)
    network = NetworkInterface.objects.filter(server=uuid)
    if serverasset:
        data['serverasset'] = serverasset
        # data['serverasset'].disk = eval(serverasset.disk)
        data['request'] = request
        data['network'] = network

    request.breadcrumbs((('首页', '/'),('主机管理',reverse('cmdb_server')),))
    return render_to_response('cmdb/assets/server_detail.html', data)

templates/cmdb/assets/server_add.html
{% extends 'base/base_site.html' %} 
<link href="/static/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="/static/css/animate.css" rel="stylesheet">
<link href="/static/css/style.css" rel="stylesheet">
{% block content %}
{% load custom_tags %}


<div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>添加主机</h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#">Config option 1</a>
                                    </li>
                                    <li><a href="#">Config option 2</a>
                                    </li>
                                </ul>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <form method="POST" action={% url 'cmdb_server_add'%} class="form-horizontal">
                            {% include 'cmdb/assets/server_content.html'%}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}


{% block javascripts %}
{{ block.super}}

<script type="text/javascript">
    $(function () { 
        $('#collapseTwo').on('show.bs.collapse', function () {
            $('.accordion-toggle').text('隐藏可由 Salt 发现的属性...');
        });
        $('#collapseTwo').on('hide.bs.collapse  ', function () {
            $('.accordion-toggle').text('显示可由 Salt 发现的属性...');
        })
    });
</script> 
{% endblock %}

templates/cmdb/assets/server_content.html
{% for i in form %}

{% if i.name == 'ip' or i.name == 'idc' or i.name == 'salt' or i.name == 'status'  or i.name == 'ops' or i.name == 'dev' %}
	<div class="form-group">
	    <label class="col-sm-2 control-label">{{i.label}}</label>
	    <div class="col-sm-8">{{i}}</div>
	    {{i.error}}
	</div>
{% else %}
	{% if forloop.counter == 7 %}
	<div id="collapseTwo" class="panel-collapse collapse">
	{% endif %}
		<div class="form-group">
		    <label class="col-sm-2 control-label">{{i.label}}</label>
		    <div class="col-sm-8">{{i}}</div>
		    {{i.error}}
		</div>
{% endif %}
{% endfor %}
</div>
<div class="panel-heading col-sm-3 control-label">
        <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" style="color: #18a689">
           显示可由 Salt 发现的属性... 
        </a>
      </h4>
</div>
<div class="form-group">
<div style="padding-left: 200px;color:red">
    <div class="col-sm-8"><b>{{ error }}</b></div>
</div>
</div>
<div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
        <button class="btn btn-white" type="submit">Cancel</button>
        <button class="btn btn-primary" type="submit">Save changes</button>
    </div>
</div>

templates/cmdb/assets/server_detail.html
{% extends 'base/base_site.html' %}
{% load custom_tags %}
{% block css %}
{{ block.super}}
<style type="text/css">
  .noshow th {
    color:#676a6c; 
    border: 0px solid transparent !important;
  }
.noshow td{
     border: 0px solid transparent !important;
 }
</style>
{% endblock%}

{% block content %}
<div class="ibox-title">
    <h5>主机信息</h5>
</div>
<div class="ibox-content">
    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper form-inline">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel blank-panel">
                    <div class="panel-heading">
                        <div class="panel-options">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#tab-1" data-toggle="tab">基本信息</a></li>
                                <li class=""><a href="#tab-2" data-toggle="tab">配置信息</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="tab-content">

                            <div class="tab-pane active" id="tab-1">

                                        <div class="col-lg-6">
                                                <table class="table noshow">

                                                    <tbody >
                                                        <tr>
                                                            <th class="col-lg-1">主机名:</th>
                                                            <td class="col-lg-2">{{serverasset.hostname}}</td>
                                                            <th class="col-lg-1">机房:</th>
                                                            <td class="col-lg-2">{{serverasset.idc}}</td>
                                                        </tr>
                                                        <tr>
                                                            <th>IP:</th>
                                                            <td>{{serverasset.ip}}</td>
                                                            <th>主机类型:</th>
                                                            <td>{{serverasset.virtual}}</td>
                                                        </tr>
                                                        <tr>
                                                            <th>运维负责人:</th>
                                                            <td>
                                                                {{serverasset.ops}}
                                                            </td>
                                                            <th>运营状态:</th>
                                                            <td>
                                                                {{serverasset.get_status_display}}
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <th>开发负责人:</th>
                                                            <td>{{serverasset.dev}}</td>
                                                            <th>Salt-Master:</th>
                                                            <td>{{serverasset.salt}}</td>
                                                        </tr>
                                                        <tr>
                                                            <th>Salt-minon版本:</th>
                                                            <td class="text-muted">{{serverasset.saltversion}}</td>

                                                        </tr>

                                                    </tbody>
                                                </table>
                                        </div>

                            </div>

                            <div class="tab-pane" id="tab-2">
                               <div class="col-lg-9">

                                    <table class="table noshow">

                                            <tbody >
                                                <tr>
                                                    <th class="col-lg-1">操作系统:</th>
                                                    <td class="col-lg-2">{{serverasset.os}}</td>
                                                    <th class="col-lg-1">shell:</th>
                                                    <td class="col-lg-2">{{serverasset.shell}}</td>
                                                </tr>
                                                <tr>
                                                    <th>产品型号:</th>
                                                    <td>{{serverasset.productname}}</td>
                                                    <th>序列号:</th>
                                                    <td>{{serverasset.sn}}</td>
                                                </tr>
                                                <tr>
                                                    <th>CPU型号:</th>
                                                    <td>
                                                        {{serverasset.cpu_model}}
                                                    </td>
                                                    <th>CPU核数:</th>
                                                    <td>
                                                        {{serverasset.cpu_nums}}
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <th>内核:</th>
                                                    <td>{{serverasset.kernel}}</td>
                                                    <th>内存:</th>
                                                    <td class="text-muted">{{serverasset.memory}}</td>
                                                </tr>
                                                 <tr>
                                                    <th>磁盘容量:</th>
                                                    <td>{{serverasset.disk|strtodict:"total"}}</td>
                                                </tr>
                                            </tbody>
                                    </table>
                                </div>      
                               <div class="col-lg-6">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th width="30%">网卡名称</th>
                                                <th width="35%">IP</th>
                                                <th width="35%">Mac地址</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for i in network %}
                                            <tr>
                                                <td>{{ i.name }}</td>
                                                <td>{{ i.address }}</td>
                                                <td>{{ i.mac }}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th width="30%">磁盘分区</th>
                                                <th width="35%">挂载点</th>
                                                <th width="35%">容量</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% with dict=serverasset.disk|strtodict:"all" %}
                                            {% for key,value in dict.items %}
                                              {% if key == 'total' %}
                                              {% else %}
                                              <tr>
                                                <td>{{ key }}</td>
                                                <td>{{ value.0 }}</td>
                                                <td>{{ value.1 }}</td>
                                              </tr>
                                              {% endif %}
                                            {% endfor %}
                                        {% endwith %}                                         
                                        </tbody>
                                    </table>
                                </div>





                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/cmdb/assets/server_edit.html
{% extends 'base/base_site.html' %} 
<link href="/static/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="/static/css/animate.css" rel="stylesheet">
<link href="/static/css/style.css" rel="stylesheet">
{% block content %}
{% load custom_tags %}


<div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>编辑主机</h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#">Config option 1</a>
                                    </li>
                                    <li><a href="#">Config option 2</a>
                                    </li>
                                </ul>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <form method="POST" action="/cmdb/server/edit/{{ uuid }}" class="form-horizontal">
                            {% include 'cmdb/assets/server_content.html'%}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}


{% block javascripts %}
{{ block.super}}

<script type="text/javascript">
    $(function () { 
        $('#collapseTwo').on('show.bs.collapse', function () {
            $('.accordion-toggle').text('隐藏可由 Salt 发现的属性...');
        });
        $('#collapseTwo').on('hide.bs.collapse  ', function () {
            $('.accordion-toggle').text('显示可由 Salt 发现的属性...');
        })
    });
</script> 
{% endblock %}

templates/cmdb/assets/server_table.html
{% load custom_tags %}
    {% for i in data.content %}
    <tr class="gradeA odd" role="row">
        <td><input type="checkbox" class="i-checks" id={{i.uuid}}></td>

        <td><a  href="/cmdb/server/detail/{{ i.uuid }}">
        {{ i.ips|ipio}}

        </a></td>
        <td>{{ i.hostname }}</td>
        <td>{{ i.ops }}</td>
        <td>{{ i.dev }}</td>
        <td>{{ i.os }}</td>
        <td>{{ i.cpu_model }}</td>
        <td>{{ i.cpu_nums }}</td>
        <td>{{ i.memory }}</td>
        <td>{{ i.disk|strtodict:"total" }}</td>
        {% if i.minion_status == 1 %}
            <td><span class="btn btn-xs btn-success">{{ i.get_minion_status_display }}</span></td>
        {% else %}
            <td><span class="btn btn-xs btn-danger">{{ i.get_minion_status_display }}</span></td>
        {% endif %}

        <td>{{ i.get_status_display }}</td>
        <td>{{ i.idc }}</td>

        <td class="center">
            <!--<a href="/cmdb/server/detail/{{ i.uuid }}" class="btn btn-xs btn-primary">详情</a>-->
            <a href="/cmdb/server/edit/{{ i.uuid }}" class="btn btn-xs btn-success">编辑</a>
            <a href="/cmdb/server/del?uuid={{ i.uuid }}" class="btn btn-xs btn-danger"  onclick="return confirm('确认删除吗？')">删除</a>

        </td>
    </tr>

    {% endfor %}